FROM manticoresearch/php-fpm:8.3.10
LABEL maintainer="Manticore Software Ltd. <contact@manticoresearch.com>"

COPY . /src
RUN ln -fs /src/docker/containers/php/config/php.ini /etc/php/php.ini && \
  ln -fs /src/docker/containers/php/config/conf.d /etc/php/conf.d && \
	cd /src/app && \
	if [ -f composer.lock ]; then \
		composer install --no-dev --optimize-autoloader; \
	fi
WORKDIR /src

ENTRYPOINT ["/src/docker/containers/php/entrypoint"]
