FROM python:3.9-slim
LABEL maintainer="Manticore Software Ltd. <contact@manticoresearch.com>"

RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY entrypoint /entrypoint

ENTRYPOINT ["/entrypoint"]
WORKDIR /src

